---
- hosts: iosxe
  gather_facts: no
  connection: local

  vars:
    cli:
      username: 
      password: 
      optional_args: {'secret':  }

  tasks:
  - name: get facts from device
    napalm_get_facts:
       dev_os: 'ios'
       provider: "{{ cli }}"
       filter: 'facts,interfaces,interfaces_ip,network_instances'
    register: result

  - name: copy output
    copy: content="{{ result |to_nice_json  }}" dest="{{inventory_hostname}}.json"
