---
- hosts: iosxe
  gather_facts: no
  connection: local

  vars:
    cli:
      username: 
      password: 
      optional_args: {'secret':  }

  tasks:
  - name: generate timestamp
    shell: date +%s 
    register: tstamp
    delegate_to: localhost
 
  - name: get interface counters 
    napalm_get_facts:
       dev_os: 'ios'
       provider: "{{ cli }}"
       filter: 'interfaces_counters'
    register: result

  - name: copy output
    copy: content="{{ result |to_nice_json  }}" dest="counters_{{ tstamp }}.json"

